# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: core-openstack
  namespace: shoot--foobar--openstack
type: Opaque
data:
  domainName: domain
  tenantName: tenant
  username: user
  password: password
  authURL: keystoneURL # mandatory